In [4]:
%pip install pandas

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 97.8 kB/s eta 0:00:0000:0200:06
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 666.4 kB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [pandas]2m3/4 [pandas]

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import random

In [4]:
nodes = pd.read_csv("dataset/nodes.csv")
edges = pd.read_csv("dataset/edges.csv")

In [5]:
nodes

index  name  groups                               _pos
0       0     1       1    array([-0.9061863,  3.5496249])
1       1     2       1  array([-0.90508109,  3.41488439])
2       2     3       1  array([-0.80582453,  3.43785648])
3       3     4       1  array([-0.91414413,  3.49198002])
4       4     5       1  array([-0.93744033,  3.65943465])
5       5     6       1  array([-0.93865958,  3.74161264])
6       6     7       1  array([-1.00989294,  3.70405542])
7       7     8       1  array([-0.96040819,  3.44806472])
8       8     9       1  array([-0.74180045,  3.4371408 ])
9       9    10       2  array([-0.79495671,  3.28583456])
10     10    11       1  array([-0.86147566,  3.69522019])
11     11    12       1  array([-1.08782867,  3.59585986])
12     12    13       1  array([-1.00609509,  3.565945  ])
13     13    14       1  array([-0.82331101,  3.49969363])
14     14    15       2  array([-0.50858156,  3.33021762])
15     15    16       2  array([-0.69973515,  3.25814535])
16     16    17       1    array([-1.0253375,  3.822035 ])
17     17    18       1  array([-1.01129734,  3.38827193])
18     18    19       2  array([-0.63596067,  3.2325222 ])
19     19    20       1  array([-0.84501658,  3.37787024])
20     20    21       2  array([-0.58022324,  3.30563348])
21     21    22       1  array([-1.04137114,  3.47222394])
22     22    23       2  array([-0.5551919 ,  3.24516724])
23     23    24       2  array([-0.56698289,  3.49048696])
24     24    25       2  array([-0.55155392,  3.58746611])
25     25    26       2  array([-0.59679323,  3.63971572])
26     26    27       2  array([-0.46670922,  3.42441603])
27     27    28       2  array([-0.63922418,  3.49088677])
28     28    29       2  array([-0.73796645,  3.52167966])
29     29    30       2  array([-0.54324813,  3.41360979])
30     30    31       2  array([-0.75415802,  3.35227941])
31     31    32       2  array([-0.6825441 ,  3.54524206])
32     32    33       2  array([-0.63438106,  3.36110647])
33     33    34       2  array([-0.66408515,  3.3917877 ])

In [6]:
edges

source  target
0        0       1
1        0       2
2        0       3
3        0       4
4        0       5
..     ...     ...
73      33      18
74      33      20
75      33      23
76      33      26
77      33      29

[78 rows x 2 columns]

In [7]:
matrix = np.zeros((len(nodes), len(nodes)))

In [8]:
n = len(nodes)

In [9]:
matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(34, 34))

In [10]:

for _, row in edges.iterrows():
        matrix[row["source"], row["target"]] = 1
        matrix[row["target"], row["source"]] = 1

In [12]:
communities = {}
for _, row in nodes.iterrows():
  if communities.get(row['groups']) == None:
    communities[row['groups']] = []
  communities[row['groups']].append(row['name'])


In [13]:
k = []
for community in communities.keys():
  k.append(community)
k = np.array(k)

In [14]:
k

array([1, 2])

In [15]:
communities

{1: [1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 17, 18, 20, 22],
 2: [10, 15, 16, 19, 21, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34]}

In [16]:
initial_population = []
for _ in range(100):
  individual = np.random.choice(k, size=n)
  initial_population.append(individual)


In [17]:
def modularity(individual, matrix, edges):
  # Q = (1/2m) * Σ(Aij - (ki*kj)/(2m))δ(ci, cj)
  m = len(edges)
  # print(m)
  Q = 0
  k = [0] * n
  for i in range(n):
    k[i] = sum(matrix[i])
  for i in range(n):
    for j in range(n):
      if individual[i] == individual[j]:
        kikj = k[i]*k[j]
        ext = kikj/(2*m)
        Q+=matrix[i,j]-ext
  return Q/(2*m)

In [18]:
selections = []

In [19]:
matrix

array([[0., 1., 1., ..., 1., 0., 0.],
       [1., 0., 1., ..., 0., 0., 0.],
       [1., 1., 0., ..., 0., 1., 0.],
       ...,
       [1., 0., 0., ..., 0., 1., 1.],
       [0., 0., 1., ..., 1., 0., 1.],
       [0., 0., 0., ..., 1., 1., 0.]], shape=(34, 34))

In [20]:
for individual in initial_population:
  score = modularity(individual, matrix, edges)
  selections.append((individual, score))
selections.sort(key=lambda x: x[1], reverse=True)

In [19]:
selections

[(array([2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 2,
         1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 1, 1]),
  np.float64(0.15055884286653562)),
 (array([1, 2, 2, 2, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 2, 2,
         1, 2, 2, 2, 1, 2, 2, 2, 1, 1, 2, 2]),
  np.float64(0.07881328073635811)),
 (array([2, 2, 1, 2, 2, 2, 2, 2, 1, 1, 2, 1, 2, 1, 1, 2, 1, 1, 2, 1, 2, 2,
         1, 2, 2, 2, 1, 2, 2, 1, 1, 2, 2, 1]),
  np.float64(0.05317225509533227)),
 (array([2, 2, 1, 2, 2, 2, 1, 2, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 1, 1, 2,
         1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1]),
  np.float64(0.049227481919789935)),
 (array([1, 2, 2, 1, 1, 2, 2, 2, 1, 2, 1, 1, 1, 1, 2, 1, 2, 2, 1, 1, 2, 2,
         1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 1, 1]),
  np.float64(0.04725509533201855)),
 (array([2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 1, 2, 2, 1, 2, 1, 2, 1, 2, 2, 2, 2,
         2, 1, 2, 2, 1, 2, 1, 1, 2, 2, 2, 1]),
  np.float64(0.04240631163708105)),
 (array([1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 

In [20]:
best_selections = selections[:len(selections)//4]

In [21]:
best_selections

[(array([2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 2,
         1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 1, 1]),
  np.float64(0.15055884286653562)),
 (array([1, 2, 2, 2, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 2, 2,
         1, 2, 2, 2, 1, 2, 2, 2, 1, 1, 2, 2]),
  np.float64(0.07881328073635811)),
 (array([2, 2, 1, 2, 2, 2, 2, 2, 1, 1, 2, 1, 2, 1, 1, 2, 1, 1, 2, 1, 2, 2,
         1, 2, 2, 2, 1, 2, 2, 1, 1, 2, 2, 1]),
  np.float64(0.05317225509533227)),
 (array([2, 2, 1, 2, 2, 2, 1, 2, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 1, 1, 2,
         1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1]),
  np.float64(0.049227481919789935)),
 (array([1, 2, 2, 1, 1, 2, 2, 2, 1, 2, 1, 1, 1, 1, 2, 1, 2, 2, 1, 1, 2, 2,
         1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 1, 1]),
  np.float64(0.04725509533201855)),
 (array([2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 1, 2, 2, 1, 2, 1, 2, 1, 2, 2, 2, 2,
         2, 1, 2, 2, 1, 2, 1, 1, 2, 2, 2, 1]),
  np.float64(0.04240631163708105)),
 (array([1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 

In [21]:
def mutation(chromosome):
  random_index = np.random.randint(0, len(chromosome))
  new_community = np.random.choice(k)
  chromosome[random_index] = new_community
  return chromosome


In [22]:
def crossover(A, B):
  random_index = np.random.randint(0, n)
  community_selected = A[random_index]
  index_selected = []
  for i in range(n):
    if A[i] == community_selected:
      index_selected.append(i)
  for index in index_selected:
    B[index] = community_selected
  return B

In [24]:
for i in range(len(best_selections)):
  if i != len(best_selections)-1:
    A = best_selections[i][0]
    B = best_selections[i+1][0]
    tmp_b = B.copy()
    B = crossover(A, B)
    A = crossover(tmp_b, A)
    best_selections[i+1] = (A, modularity(A, matrix, edges))
    best_selections[i] = (B, modularity(B, matrix, edges))
  else:
    A = best_selections[i][0]
    B = best_selections[0][0]
    tmp_b = B.copy()
    B = crossover(A, B)
    A = crossover(tmp_b, A)
    best_selections[0] = (A, modularity(A, matrix, edges))
    best_selections[i] = (B, modularity(B, matrix, edges))
    
best_selections.sort(key=lambda x: x[1], reverse=True)

In [25]:
best_selections

[(array([1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 2, 1, 1, 1,
         2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1]),
  np.float64(0.05424063116370849)),
 (array([1, 2, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2,
         1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1]),
  np.float64(0.04265285996055247)),
 (array([1, 2, 2, 2, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 2, 2,
         1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 1, 1]),
  np.float64(0.04068047337278116)),
 (array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 1, 2, 1, 2, 2, 1, 2, 2,
         1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 1]),
  np.float64(0.03517422748192002)),
 (array([1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2,
         1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
  np.float64(0.02465483234714006)),
 (array([2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 2, 2, 1, 2, 2, 1,
         2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 1]),
  np.float64(0.015696909927679272)),
 (array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 

In [26]:
# mutation 
mutation_gen = best_selections.copy()
for i in range(len(mutation_gen)):
  chromosome = mutation_gen[i][0]
  mutated_chromosome = mutation(chromosome)
  mutation_gen[i] = (mutated_chromosome, modularity(mutated_chromosome, matrix, edges))


In [27]:
mutation_gen

[(array([1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 2, 1, 1, 1,
         2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1]),
  np.float64(0.05424063116370849)),
 (array([1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2,
         1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1]),
  np.float64(-0.00098619329388546)),
 (array([1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 2, 2,
         1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 1, 1]),
  np.float64(-0.009861932938855835)),
 (array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 1, 2, 1, 2, 2, 1, 2, 2,
         1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 1]),
  np.float64(0.03517422748192002)),
 (array([1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2,
         1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1]),
  np.float64(0.018408941485864607)),
 (array([2, 1, 2, 2, 1, 1, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 2, 2, 1, 2, 2, 1,
         2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 1]),
  np.float64(-0.00032873109796185604)),
 (array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,

In [26]:
# local search

T = 800000
x = 0.99
l = 10
step = 0.02

initial_population = []
for _ in range(1000):
  individual = np.random.choice(k , size=n)
  initial_population.append(individual)

res = (0, [])
anneal_time = 1

while T > 1:
  g1_index = np.random.randint(0, len(initial_population))
  g2_index = np.random.randint(0, len(initial_population))
  g1 = initial_population[g1_index]
  g2 = initial_population[g2_index]
  limit = 0.0
  if limit >= 1.0:
    T = T * x
    continue

  for i in range(l):
    g2_temp = g2.copy()
    G1 = crossover(g1, g2)
    G2 = crossover(g2_temp, g1)
    mutation_rate = random.uniform(0, 1)
    if mutation_rate < 0.3:
      G1 = mutation(G1)
      G1 = mutation(G1)
    else:
      G1 = mutation(G1)
      G2 = mutation(G2)
    p = modularity(G1, matrix, edges) - modularity(G2, matrix, edges)
    r = random.uniform(0, 1)
    if p > limit or np.exp(p/T) >  r:
      g1 = G1
      limit += step
  T = T * x
  q = modularity(g1, matrix, edges)
  if T < 1:
    print(f"Anneal {anneal_time}: Modularity = {q}, Gene = {g1}")
    if q-res[0] >= 0.2:
      print("Found")
      res = (q, g1)
      break
    else: 
      anneal_time += 1
      T = 800000

print(res)

Anneal 1: Modularity = -0.03558514135437173, Gene = [2 2 1 2 1 2 1 1 2 2 2 2 2 2 2 1 1 1 2 1 1 1 2 2 2 1 2 1 2 2 2 2 2 2]
Anneal 2: Modularity = 0.007560815253123274, Gene = [1 1 1 1 2 1 1 1 2 1 2 1 2 1 1 1 1 1 2 1 1 1 2 1 1 1 1 1 1 1 1 1 1 2]
Anneal 3: Modularity = 0.08999013806706137, Gene = [1 2 2 1 1 1 1 1 2 1 2 2 2 2 2 2 2 1 2 2 1 1 2 2 2 2 2 2 2 2 2 2 2 2]
Anneal 4: Modularity = -0.08514135437212332, Gene = [2 1 2 1 2 1 2 2 2 2 2 2 1 2 2 1 2 2 2 1 2 2 2 2 1 2 2 1 2 2 2 2 1 1]
Anneal 5: Modularity = 0.01150558842866553, Gene = [2 1 2 2 2 2 1 1 2 2 2 2 2 2 2 2 2 2 2 1 2 2 1 2 2 2 2 2 2 2 2 2 2 2]
Anneal 6: Modularity = 0.058431952662722116, Gene = [1 1 2 2 1 2 2 1 2 1 2 2 1 2 1 1 2 1 1 1 2 1 1 2 2 2 2 2 2 2 2 2 1 2]
Anneal 7: Modularity = 0.0018902038132808407, Gene = [1 2 1 2 1 2 2 1 1 1 2 1 1 1 1 1 2 1 2 1 2 1 2 2 2 2 2 2 1 1 2 2 1 1]
Anneal 8: Modularity = 0.005588428665351865, Gene = [1 2 1 1 1 1 1 2 1 1 1 1 1 1 1 1 2 1 1 2 1 1 1 2 1 2 1 2 1 2 1 1 2 1]
Anneal 9: Modularity = 0.

KeyboardInterrupt: 